{% set name = "msal_extensions" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/AzureAD/microsoft-authentication-extensions-for-python/archive/{{ version }}.tar.gz
  sha256: e57b97bc4c933c1e1a43be3098751fd4fb318042a2551de1ff34f1875ee20ed4

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - msal >=0.8,<1.0
    - portalocker

test:
  imports:
    - msal_extensions

about:
  home: https://github.com/AzureAD/microsoft-authentication-extensions-for-python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Microsoft Authentication extensions for MSAL.Python '
  description: |
    Microsoft Authentication extensions for MSAL.Python 
  doc_url: https://github.com/AzureAD/microsoft-authentication-extensions-for-python
  dev_url: https://github.com/AzureAD/microsoft-authentication-extensions-for-python

extra:
  recipe-maintainers:
    - roederja2
