{% set name = "msal_extensions" %}
{% set version = "1.2.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6f41b320bfd2933d631a215c91ca0dd3e67d84bd1a2f50ce917d5874ec646bef

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
  skip: true  # [py<37]

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools
  run:
    - python
    - msal >=1.29,<2
    - portalocker >=1.4,<3

test:
  imports:
    - msal_extensions
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/AzureAD/microsoft-authentication-extensions-for-python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Microsoft Authentication extensions for MSAL.Python
  description: |
    Microsoft Authentication extensions for MSAL.Python 
  doc_url: https://github.com/AzureAD/microsoft-authentication-extensions-for-python
  dev_url: https://github.com/AzureAD/microsoft-authentication-extensions-for-python

extra:
  recipe-maintainers:
    - dhirschfeld
    - roederja
