travis:
  secure:
    BINSTAR_TOKEN: fledLRhP/bcP9Pi6LEVWddLdxq7fHh9+FIs2dypP4lVOUhDf7wq8Kl+OudF62Q9ubiGov6y7CxGIhwMNaf56sfXCGibcBTbMrv17IQu+OqaHYNtrOIQSFPe4ypcjOzw8CEGtdOPP7fbgSQMqq9XkoVuEHyhcnbkl86MEGQn19roUzVcysOStS0jvk0x8cEXpRUHeDOr5YgecHkwAWRd+yQ/LMJvtzFS+0mrc/wY4DO44Ba74t8ItQBSktESUGrF5PLjauM+ez+iec1TRsLhMbu6CgMlTNUF6O3ezUaCHK4bNflb4vxVzGk/lBcI24o4fChpfiIsh5+pOZy7Gz+86sjSl/CVJcUlT+bhgmM0DpFP+N82wuX/cs//h+CSdwbBXPW3GjxMWMo5YlwiJN8I2fpTp17gAkyBX+7XbO/tOr3dJ6fN2IQ4qoGqfE4bfW0TOlw8qGhOfINtw8FwvJjONKmJlIPV5eIBu0N06ZS4X8GJZLYaSBdSe/es+8v/JhSuLULOb9JS5zG5yPI1TgW6J6d/g3B8UTy4n6xwpBJlM+f/C+CWvjm9IJ+hqyporye4q6kT8DtWqYfWWl+apw2jIoEP4Ei5dsEHMYvvjKAR9NwH0GtGHCugBb1WkIUwhdD2jVumbOXIwmDilzAfZyoMZfOU3vgKQreqpLTdk0sBoLyg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
